#!/usr/bin/env python3
"""
Zero-Shadow AEAD analysis: the schedule split, the schedulability frontier, and the
area price of the engine. Writes paper/tables.tex and results/figures/.
"""
import csv, os, math
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A_R, B_R, RATE_B = 12, 8, 16          # init/final rounds, per-block rounds, rate bytes
T_NODE = 111                          # measured inference shadow of the reference node

# measured RTL schedule (sim/run_sim.sh); cycles
SCHED = {}
with open(os.path.join(ROOT, "results", "schedule.csv")) as f:
    for r in csv.DictReader(f):
        SCHED[int(r["rpc"])] = dict(pre=int(r["precompute_cyc"]),
                                    vis=[int(r[f"visible_{i}blk"]) for i in range(1, 6)])

AREA = {}
p = os.path.join(ROOT, "results", "aead_sweep.csv")
if os.path.exists(p):
    for r in csv.DictReader(open(p)):
        AREA[int(r["rpc"])] = dict(lut=int(r["lut"]), ff=int(r["ff"]),
                                   fmax=float(r["fmax_mhz"]), power=float(r["power_w"]))

def visible_rounds(M):  return B_R * M + A_R          # cannot be precomputed
def min_R(M, T):
    for R in range(1, 13):
        if math.ceil(visible_rounds(M) / R) <= T: return R
    return None

print("=== measured schedule (cycles) ===")
print("  rpc  precompute   visible by record blocks 1..5")
for r in sorted(SCHED):
    print(f"  {r:3d} {SCHED[r]['pre']:9d}   {SCHED[r]['vis']}")

print("\n=== precompute share hidden in the previous inference ===")
for r in sorted(SCHED):
    tot = SCHED[r]["pre"] + SCHED[r]["vis"][0]
    print(f"  rpc={r:2d}: {SCHED[r]['pre']}/{tot} cycles = "
          f"{100*SCHED[r]['pre']/tot:.0f}% of a single-block encryption removed")

if AREA:
    print("\n=== area price of the engine ===")
    print("  rpc    LUT    FF   Fmax   power   vis(1blk)  vis(5blk)")
    for r in sorted(AREA):
        a = AREA[r]; s = SCHED.get(r)
        print(f"  {r:3d} {a['lut']:6d} {a['ff']:5d} {a['fmax']:6.0f} {a['power']:7.3f} "
              f"{s['vis'][0]:10d} {s['vis'][4]:10d}" if s else "")

# ---------------------------------------------------------------- tables -----
T = ["% AUTO-GENERATED by model/analyze.py"]
rows = "".join(r"%d & %d & %d & %d\\" % (r, SCHED[r]["pre"], SCHED[r]["vis"][0],
                                          SCHED[r]["vis"][4]) + "\n"
               for r in sorted(SCHED))
T.append(r"""\begin{table}[tb]\centering\setlength{\tabcolsep}{5pt}\footnotesize
\caption{Measured schedule split. Initialization depends only on key and nonce, so it is
precomputed inside the previous inference; only the record-dependent part stays visible.}
\label{tab:sched}
\begin{tabular}{rrrr}
\toprule
rounds/cyc & precompute (hidden) & visible, 1 blk & visible, 5 blk\\\midrule
%s\bottomrule\end{tabular}\end{table}""" % rows)

# frontier: minimum engine to hide a record behind a given shadow
shadows = [32, 64, 111, 256]
hdr = " & ".join(f"$T{{=}}{t}$" for t in shadows)
body = ""
for M in (1, 2, 4, 8, 16, 32, 64, 128):
    cells = []
    for t in shadows:
        R = min_R(M, t)
        cells.append(str(R) if R else r"\textemdash")
    body += r"%d (%d\,B) & %s\\" % (M, M * RATE_B, " & ".join(cells)) + "\n"
T.append(r"""\begin{table}[tb]\centering\setlength{\tabcolsep}{5pt}\footnotesize
\caption{Smallest engine (rounds per cycle) that keeps authenticated encryption invisible,
by record size and available shadow $T$ in cycles. A dash means no engine up to 12
rounds per cycle suffices.}
\label{tab:frontier}
\begin{tabular}{lrrrr}
\toprule
record & %s\\\midrule
%s\bottomrule\end{tabular}\end{table}""" % (hdr, body))

if AREA:
    arows = ""
    for r in sorted(AREA):
        a, s_ = AREA[r], SCHED[r]
        n1 = s_["vis"][0] / a["fmax"] * 1e3
        n5 = s_["vis"][4] / a["fmax"] * 1e3
        arows += r"%d & %d & %.0f & %.3f & %d & %.1f & %.1f\\" % (
            r, a["lut"], a["fmax"], a["power"], s_["vis"][0], n1, n5) + "\n"
    T.append(r"""\begin{table}[tb]\centering\setlength{\tabcolsep}{4pt}\footnotesize
\caption{Area price and the wall-clock consequence (xck26, OOC place\&route; zero DSP and
zero block RAM everywhere). A larger engine always reduces the visible \emph{cycle} count
but degrades $F_{\max}$, so visible \emph{time} is minimized by a small engine.}
\label{tab:area}
\begin{tabular}{rrrrrrr}
\toprule
rnd/cyc & LUT & $F_{\max}$ & power & vis.\ cyc & vis.\ ns & 5-blk ns\\\midrule
%s\bottomrule\end{tabular}\end{table}""" % arows)

os.makedirs(os.path.join(ROOT, "paper"), exist_ok=True)
open(os.path.join(ROOT, "paper", "tables.tex"), "w").write("\n".join(T) + "\n")
print(f"\nwrote paper/tables.tex ({len(T)-1} tables)")

# ---------------------------------------------------------------- figure -----
try:
    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:
    raise SystemExit
FIG = os.path.join(ROOT, "results", "figures"); os.makedirs(FIG, exist_ok=True)
C_BLUE, C_ORANGE, C_AQUA, INK, MUTED = "#2a78d6", "#eb6834", "#1baf7a", "#0b0b0b", "#898781"
plt.rcParams.update({"font.size": 7.5, "axes.edgecolor": "#c3c2b7", "axes.linewidth": 0.6,
                     "xtick.color": MUTED, "ytick.color": MUTED, "text.color": INK,
                     "axes.labelcolor": "#52514e"})
fig, (a1, a2) = plt.subplots(1, 2, figsize=(7.0, 2.35))

# left: schedule split, stacked
rs = sorted(SCHED)
pre = [SCHED[r]["pre"] for r in rs]
vis = [SCHED[r]["vis"][0] for r in rs]
x = np.arange(len(rs))
a1.bar(x, pre, 0.6, color=C_AQUA, label="initialization (precomputed, hidden)")
a1.bar(x, vis, 0.6, bottom=pre, color=C_ORANGE, label="record-dependent (visible)")
a1.set_xticks(x); a1.set_xticklabels([str(r) for r in rs])
a1.set_xlabel("engine size (rounds per cycle)"); a1.set_ylabel("cycles, one-block record")
a1.set_title("Initialization leaves the critical path", fontsize=8)
a1.legend(fontsize=6.2, frameon=False)
for s in ("top", "right"): a1.spines[s].set_visible(False)

# right: schedulability frontier
Ms = np.arange(1, 200)
for T_sh, col in ((32, C_ORANGE), (111, C_BLUE), (256, C_AQUA)):
    need = [min_R(int(m), T_sh) or np.nan for m in Ms]
    a2.plot(Ms, need, lw=1.4, color=col, label=f"shadow = {T_sh} cyc")
a2.set_xscale("log"); a2.set_xlabel("record size (16-byte blocks, log)")
a2.set_ylabel("smallest engine (rounds/cyc)")
a2.set_ylim(0, 13); a2.set_title("Bigger batches demand a bigger engine", fontsize=8)
a2.legend(fontsize=6.4, frameon=False, loc="upper left")
for s in ("top", "right"): a2.spines[s].set_visible(False)

fig.tight_layout()
for e in ("pdf", "png"):
    fig.savefig(os.path.join(FIG, f"fig_schedule.{e}"), bbox_inches="tight", dpi=400)
print("wrote results/figures/fig_schedule.pdf")
